bookie.version=1.1.9
spring.threads.virtual.enabled=true
spring.main.lazy-initialization=true
spring.jmx.enabled=false
bookie.session.timeout-seconds=1800
spring.web.resources.static-locations=file:src/main/resources/static/,classpath:/static/
spring.web.resources.cache.cachecontrol.max-age=7d
spring.web.resources.cache.cachecontrol.cache-public=true
logging.level.root=INFO
bookie.cache-enabled=true
bookie.open-when-hidden=false
bookie.order-requests=true
bookie.stress.trades.per.second=0
bookie.stress.restrict.bonds=10