spring.threads.virtual.enabled=true
bookie.session.timeout-seconds=1800
spring.web.resources.static-locations=file:src/main/resources/static/
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG