bookie.version=1.1.4
spring.threads.virtual.enabled=true
spring.main.lazy-initialization=true
spring.jmx.enabled=false
bookie.session.timeout-seconds=1800
spring.web.resources.static-locations=file:src/main/resources/static/,classpath:/static/
spring.web.resources.cache.cachecontrol.max-age=1d
spring.web.resources.cache.cachecontrol.cache-public=true
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG